# Generated by Django 2.0.9 on 2018-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('tutoring', 'Tutoring'), ('wildlife_conservation', 'Wildlife Conversation'), ('construction', 'Construction'), ('ocean_cleaning', 'Ocean Cleaning'), ('street_cleaning', 'Street Cleaning')], default='tutoring', max_length=12),
        ),
    ]
