# Generated by Django 2.0.9 on 2018-11-07 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181107_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='estimate_hours',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('tutoring', 'Tutoring'), ('wildlife_conservation', 'Wildlife Conservation'), ('construction', 'Construction'), ('ocean_cleaning', 'Ocean Cleaning'), ('street_cleaning', 'Street Cleaning')], default='tutoring', max_length=50),
        ),
    ]
