# Generated by Django 2.0.9 on 2018-11-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181022_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('schools', 'SCHOOLS'), ('nature', 'NATURE'), ('construction', 'CONSTRUCTION'), ('cleaning', 'CLEANING')], default='schools', max_length=12),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
