# Generated by Django 2.0.9 on 2018-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181022_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
