# Generated by Django 2.0.9 on 2018-11-07 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181107_1231'),
        ('post', '0006_auto_20181107_0103'),
    ]

    operations = [
    ]
