# Generated by Django 2.0.9 on 2018-11-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20181107_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geolocation',
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
