# Generated by Django 2.0.9 on 2018-11-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
