# Generated by Django 2.0.9 on 2018-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
